// ============================================================================
//   我的世界 方块映射表（手工建，Round195）
//   来源：Minecraft Wiki 方块注册表（1.12.2 数字 ID + 1.13「扁平化」命名空间 ID）
//   每个 MTL 材质名（来自 ss1.mtl / glass1.mtl）逐一映射到正确的方块身份，并标注版本差异。
//
//   字段：
//     mtl        : .mtl 中的精确材质名（PascalCase）
//     legacyId   : 1.12.2 数字方块 ID（-1 = 该方块在 1.12 不存在 / 1.13+ 才加）
//     legacyData : 1.12 data value（变体用），-1 = 无 data（单方块）
//     id113      : 1.13+ 规范命名空间 ID（如 "minecraft:stone"）
//     alt        : 与本图集同一张贴图共享的其它 1.13 ID，"|" 分隔（变体家族）；"" = 无
//     note       : 跨版本差异 / 备注
//
//   重要：1.13「扁平化」移除了数字 ID，原 data value 变体各自成为独立 ID
//     （如 wool[0..15] → white_wool..black_wool；planks[0..5] → *_planks）。
//   本图集每个 MTL 仅一张贴图，故一个 MTL 槽位反向覆盖整族变体。
// ============================================================================
#pragma once

struct McBlockMapEntry {
    const char* mtl;
    int         legacyId;
    int         legacyData;
    const char* id113;
    const char* alt;
    const char* note;
};

// 顺序按 ss1.mtl 出现顺序，便于与图集网格对照；glass1.mtl 的 6 个附在末尾。
static const McBlockMapEntry g_mcBlockMap[] = {
    // ---- 基础地形 ----
    { "Stone",                       1,   -1,  "minecraft:stone",                  "",                                   "1.12:stone(1)；1.13 未改名。1.13 起 stone 拆分为 granite/diorite/andesite 等" },
    { "Grass_Block",                 2,   -1,  "minecraft:grass_block",           "",                                   "1.12:grass(2)；1.13 重命名为 grass_block" },
    { "Dirt",                        3,   -1,  "minecraft:dirt",                   "minecraft:coarse_dirt|minecraft:rooted_dirt", "1.12:dirt(3)；1.13 dirt 拆分为 dirt/coarse_dirt/podzol；coarse_dirt 共用此贴图" },
    { "Cobblestone",                 4,   -1,  "minecraft:cobblestone",           "",                                   "1.12:cobblestone(4)；1.13 未改名" },
    { "Oak_Planks",                  5,   0,   "minecraft:oak_planks",            "",                                   "1.12:planks(5,d0)；1.13 planks 拆为 *_planks" },
    { "Bedrock",                     7,   -1,  "minecraft:bedrock",               "",                                   "1.12:bedrock(7)；1.13 未改名" },
    { "Stationary_Water",            9,   -1,  "minecraft:water",                 "minecraft:flowing_water",              "1.12:water(9,静)/flowing_water(8,流)；1.13 合并为 water" },
    { "Sand",                        12,  0,   "minecraft:sand",                  "",                                   "1.12:sand(12,d0)；1.13 拆 sand(0)/red_sand(1)；red_sand 见 Red_Sandstone 区" },
    { "Oak_Log",                     17,  0,   "minecraft:oak_log",               "",                                   "1.12:log(17,d0)；1.13 log 拆为 *_log" },
    { "Oak_Leaves",                  18,  0,   "minecraft:oak_leaves",            "",                                   "1.12:leaves(18,d0)；1.13 leaves 拆为 *_leaves" },
    { "Sponge",                      19,  0,   "minecraft:sponge",                "minecraft:wet_sponge",                 "1.12:sponge(19,d0/1)；1.13 拆 sponge/wet_sponge" },
    { "Glass",                       20,  -1,  "minecraft:glass",                 "",                                   "1.12:glass(20)；1.13 未改名" },
    { "Block_of_Lapis_Lazuli",       22,  -1,  "minecraft:lapis_block",           "",                                   "1.12:lapis_block(22)" },
    { "Dispenser",                   23,  -1,  "minecraft:dispenser",             "",                                   "1.12:dispenser(23)" },
    { "Sandstone",                   24,  0,   "minecraft:sandstone",             "minecraft:chiseled_sandstone|minecraft:cut_sandstone|minecraft:smooth_sandstone", "1.12:sandstone(24,d0-2)；1.13 拆 sandstone/chiseled/cut/smooth" },
    { "Note_Block",                  25,  -1,  "minecraft:note_block",           "",                                   "1.12:noteblock(25)" },
    { "Bed",                         26,  -1,  "minecraft:bed",                   "",                                   "1.12:bed(26)；1.13 床变为物品/实体，方块态保留" },
    { "Powered_Rail",                27,  -1,  "minecraft:golden_rail",          "",                                   "1.12:golden_rail(27)；1.13 重命名 golden_rail" },
    { "Detector_Rail",               28,  -1,  "minecraft:detector_rail",         "",                                   "1.12:detector_rail(28)" },
    { "Sticky_Piston",               29,  -1,  "minecraft:sticky_piston",        "",                                   "1.12:sticky_piston(29)" },
    { "Cobweb",                      30,  -1,  "minecraft:cobweb",               "",                                   "1.12:web(30)；1.13 重命名 cobweb" },
    { "Grass",                       31,  1,   "minecraft:grass",                 "minecraft:fern",                       "1.12:tallgrass(31,d1=草,d2=蕨)；1.13 拆 grass/fern" },
    { "Piston",                      33,  -1,  "minecraft:piston",               "",                                   "1.12:piston(33)" },
    { "Piston_Head",                 34,  -1,  "minecraft:piston_head",          "",                                   "1.12:piston_head(34)" },
    { "Wool",                        35,  0,   "minecraft:white_wool",            "minecraft:orange_wool|minecraft:magenta_wool|minecraft:light_blue_wool|minecraft:yellow_wool|minecraft:lime_wool|minecraft:pink_wool|minecraft:gray_wool|minecraft:light_gray_wool|minecraft:cyan_wool|minecraft:purple_wool|minecraft:blue_wool|minecraft:brown_wool|minecraft:green_wool|minecraft:red_wool|minecraft:black_wool", "1.12:wool(35,d0-15)；1.13 拆 16 色 *_wool（本图集仅一张，覆盖全部）" },
    { "Dandelion",                   37,  -1,  "minecraft:dandelion",            "",                                   "1.12:yellow_flower(37)；1.13 重命名 dandelion" },
    { "Poppy",                       38,  0,   "minecraft:poppy",                "minecraft:blue_orchid|minecraft:allium|minecraft:azure_bluet|minecraft:red_tulip|minecraft:orange_tulip|minecraft:white_tulip|minecraft:pink_tulip|minecraft:oxeye_daisy", "1.12:red_flower(38,d0-8)；1.13 拆 9 种花。本图集仅一张（通用花），覆盖全部" },
    { "Block_of_Gold",               41,  -1,  "minecraft:gold_block",           "",                                   "1.12:gold_block(41)" },
    { "Block_of_Iron",               42,  -1,  "minecraft:iron_block",           "",                                   "1.12:iron_block(42)" },
    { "Double_Stone_Slab",           43,  -1,  "minecraft:double_stone_slab",    "minecraft:smooth_stone_slab|minecraft:cut_copper_slab", "1.12:double_stone_slab(43,d0-7)；1.13 拆多种 slab；smooth_stone_slab/cut_copper_slab 共用此贴图" },
    { "Stone_Slab",                  44,  0,   "minecraft:stone_slab",           "minecraft:cobblestone_slab|minecraft:brick_slab|minecraft:stone_brick_slab|minecraft:nether_brick_slab|minecraft:quartz_slab|minecraft:petrified_oak_slab|minecraft:cut_sandstone_slab|minecraft:smooth_stone|minecraft:cut_copper", "1.12:stone_slab(44,d0-7)；1.13 拆多种 slab。本图集仅一张（石半砖），覆盖全部同款" },
    { "Bricks",                      45,  -1,  "minecraft:brick",               "minecraft:brick_block",                 "1.12:brick_block(45)；1.13 重命名 brick" },
    { "TNT",                         46,  -1,  "minecraft:tnt",                  "",                                   "1.12:tnt(46)" },
    { "Bookshelf",                   47,  -1,  "minecraft:bookshelf",            "",                                   "1.12:bookshelf(47)" },
    { "Mossy_Cobblestone",           48,  -1,  "minecraft:mossy_cobblestone",    "",                                   "1.12:mossy_cobblestone(48)" },
    { "Obsidian",                    49,  -1,  "minecraft:obsidian",             "",                                   "1.12:obsidian(49)" },
    { "Fire",                        51,  -1,  "minecraft:fire",                 "",                                   "1.12:fire(51)" },
    { "Oak_Stairs",                  53,  -1,  "minecraft:oak_stairs",           "",                                   "1.12:oak_stairs(53)" },
    { "Chest",                       54,  -1,  "minecraft:chest",               "",                                   "1.12:chest(54)" },
    { "Redstone_Wire",               55,  -1,  "minecraft:redstone_wire",        "",                                   "1.12:redstone_wire(55)" },
    { "Crafting_Table",              58,  -1,  "minecraft:crafting_table",       "",                                   "1.12:crafting_table(58)" },
    { "Furnace",                     61,  -1,  "minecraft:furnace",              "minecraft:lit_furnace",                "1.12:furnace(61)/lit_furnace(62)；1.13 合并（lit 为方块状态）" },
    { "Oak_Door",                    64,  -1,  "minecraft:oak_door",             "",                                   "1.12:wooden_door(64)；1.13 重命名 oak_door" },
    { "Ladder",                      65,  -1,  "minecraft:ladder",              "",                                   "1.12:ladder(65)" },
    { "Rail",                        66,  -1,  "minecraft:rail",                 "",                                   "1.12:rail(66)" },
    { "Wall_Sign",                   68,  -1,  "minecraft:wall_sign",            "",                                   "1.12:wall_sign(68)" },
    { "Lever",                       69,  -1,  "minecraft:lever",                "",                                   "1.12:lever(69)" },
    { "Iron_Door",                   71,  -1,  "minecraft:iron_door",            "",                                   "1.12:iron_door(71)" },
    { "Redstone_Torch_(inactive)",   75,  -1,  "minecraft:unlit_redstone_torch", "",                                  "1.12:unlit_redstone_torch(75)；1.13 合并入 redstone_torch 状态" },
    { "Redstone_Torch_(active)",      76,  -1,  "minecraft:redstone_torch",       "",                                  "1.12:redstone_torch(76)" },
    { "Stone_Button",                77,  -1,  "minecraft:stone_button",         "",                                  "1.12:stone_button(77)" },
    { "Clay",                        82,  -1,  "minecraft:clay",                 "",                                   "1.12:clay(82)" },
    { "Jukebox",                     84,  -1,  "minecraft:jukebox",              "",                                   "1.12:jukebox(84)" },
    { "Fence",                       85,  -1,  "minecraft:oak_fence",            "",                                   "1.12:fence(85)；1.13 重命名 oak_fence" },
    { "Netherrack",                  87,  -1,  "minecraft:netherrack",           "",                                   "1.12:netherrack(87)" },
    { "Soul_Sand",                   88,  -1,  "minecraft:soul_sand",             "",                                   "1.12:soul_sand(88)" },
    { "Glowstone",                   89,  -1,  "minecraft:glowstone",            "",                                   "1.12:glowstone(89)" },
    { "Redstone_Repeater_(inactive)",93,  -1,  "minecraft:unpowered_repeater",  "",                                   "1.12:unpowered_repeater(93)；1.13 合并入 repeater 状态" },
    { "Redstone_Repeater_(active)",  94,  -1,  "minecraft:powered_repeater",    "minecraft:repeater",                   "1.12:powered_repeater(94)；1.13 合并为 repeater（powered 为状态）" },
    { "Stained_Glass",               95,  0,   "minecraft:white_stained_glass", "minecraft:orange_stained_glass|minecraft:magenta_stained_glass|minecraft:light_blue_stained_glass|minecraft:yellow_stained_glass|minecraft:lime_stained_glass|minecraft:pink_stained_glass|minecraft:gray_stained_glass|minecraft:light_gray_stained_glass|minecraft:cyan_stained_glass|minecraft:purple_stained_glass|minecraft:blue_stained_glass|minecraft:brown_stained_glass|minecraft:green_stained_glass|minecraft:red_stained_glass|minecraft:black_stained_glass", "1.12:stained_glass(95,d0-15)；1.13 拆 16 色 *_stained_glass（本图集一张，覆盖全色）" },
    { "Oak_Trapdoor",                96,  -1,  "minecraft:oak_trapdoor",         "",                                   "1.12:trapdoor(96)；1.13 重命名 oak_trapdoor" },
    { "Stone_Bricks",                98,  0,   "minecraft:stone_bricks",         "minecraft:mossy_stone_bricks|minecraft:cracked_stone_bricks|minecraft:chiseled_stone_bricks|minecraft:infested_stone_bricks|minecraft:infested_mossy_stone_bricks|minecraft:infested_cracked_stone_bricks|minecraft:infested_chiseled_stone_bricks", "1.12:stonebrick(98,d0-3)；1.13 拆 stone_bricks + 虫蚀/裂纹/浮雕等多种。本图集仅一张（普通石砖），覆盖同款" },
    { "Iron_Bars",                   101, -1,  "minecraft:iron_bars",            "",                                   "1.12:iron_bars(101)" },
    { "Glass_Pane",                  102, -1,  "minecraft:glass_pane",           "",                                   "1.12:glass_pane(102)" },
    { "Melon",                       103, -1,  "minecraft:melon",                "minecraft:melon_block",                 "1.12:melon_block(103)；1.13 重命名 melon" },
    { "Fence_Gate",                  107, -1,  "minecraft:oak_fence_gate",       "",                                   "1.12:fence_gate(107)；1.13 重命名 oak_fence_gate" },
    { "Brick_Stairs",                108, -1,  "minecraft:brick_stairs",         "",                                   "1.12:brick_stairs(108)" },
    { "Stone_Brick_Stairs",          109, -1,  "minecraft:stone_brick_stairs",   "",                                   "1.12:stone_brick_stairs(109)" },
    { "Nether_Brick_Fence",          113, -1,  "minecraft:nether_brick_fence",   "",                                   "1.12:nether_brick_fence(113)" },
    { "Nether_Brick_Stairs",         114, -1,  "minecraft:nether_brick_stairs",  "",                                   "1.12:nether_brick_stairs(114)" },
    { "Brewing_Stand",               117, -1,  "minecraft:brewing_stand",        "",                                   "1.12:brewing_stand(117)" },
    { "Cauldron",                    118, -1,  "minecraft:cauldron",             "",                                   "1.12:cauldron(118)" },
    { "End_Portal_Frame",            120, -1,  "minecraft:end_portal_frame",     "",                                   "1.12:end_portal_frame(120)" },
    { "Redstone_Lamp_(inactive)",    123, -1,  "minecraft:redstone_lamp",        "minecraft:lit_redstone_lamp",         "1.12:redstone_lamp(123)/lit_redstone_lamp(124)；1.13 合并（lit 为状态）" },
    { "Redstone_Lamp_(active)",      124, -1,  "minecraft:lit_redstone_lamp",    "",                                   "1.12:lit_redstone_lamp(124)；1.13 并入 redstone_lamp 的 lit 状态" },
    { "Double_Oak_Slab",             125, 0,   "minecraft:double_oak_slab",      "minecraft:double_spruce_slab|minecraft:double_birch_slab|minecraft:double_jungle_slab|minecraft:double_acacia_slab|minecraft:double_dark_oak_slab", "1.12:double_wooden_slab(125,d0-5)；1.13 拆各种 double_*_slab" },
    { "Oak_Slab",                    126, 0,   "minecraft:oak_slab",             "minecraft:spruce_slab|minecraft:birch_slab|minecraft:jungle_slab|minecraft:acacia_slab|minecraft:dark_oak_slab|minecraft:petrified_oak_slab", "1.12:wooden_slab(126,d0-5)；1.13 拆各种 *_slab" },
    { "Sandstone_Stairs",            128, -1,  "minecraft:sandstone_stairs",     "",                                   "1.12:sandstone_stairs(128)" },
    { "Tripwire_Hook",               131, -1,  "minecraft:tripwire_hook",        "",                                   "1.12:tripwire_hook(131)" },
    { "Block_of_Emerald",            133, -1,  "minecraft:emerald_block",        "",                                   "1.12:emerald_block(133)" },
    { "Spruce_Stairs",               134, -1,  "minecraft:spruce_stairs",        "",                                   "1.12:spruce_stairs(134)" },
    { "Birch_Stairs",                135, -1,  "minecraft:birch_stairs",         "",                                   "1.12:birch_stairs(135)" },
    { "Jungle_Stairs",               136, -1,  "minecraft:jungle_stairs",        "",                                   "1.12:jungle_stairs(136)" },
    { "Command_Block",               137, -1,  "minecraft:command_block",        "minecraft:repeating_command_block|minecraft:chain_command_block", "1.12:command_block(137)；1.13 加 repeating/chain" },
    { "Beacon",                      138, -1,  "minecraft:beacon",               "",                                   "1.12:beacon(138)" },
    { "Cobblestone_Wall",            139, 0,   "minecraft:cobblestone_wall",     "minecraft:mossy_cobblestone_wall|minecraft:andesite_wall|minecraft:stone_brick_wall|minecraft:mossy_stone_brick_wall|minecraft:nether_brick_wall|minecraft:red_nether_brick_wall|minecraft:sandstone_wall|minecraft:prismarine_wall|minecraft:granite_wall|minecraft:diorite_wall|minecraft:blackstone_wall|minecraft:polished_blackstone_wall", "1.12:cobblestone_wall(139,d0-1)；1.13 拆多种 wall。本图集一张（圆石墙），覆盖同款" },
    { "Flower_Pot",                  140, -1,  "minecraft:flower_pot",           "",                                   "1.12:flower_pot(140)" },
    { "Oak_Button",                  143, -1,  "minecraft:oak_button",           "",                                   "1.12:wooden_button(143)；1.13 重命名 oak_button" },
    { "Mob_Head",                    144, -1,  "minecraft:skeleton_skull",       "minecraft:wither_skeleton_skull|minecraft:zombie_head|minecraft:player_head|minecraft:creeper_head|minecraft:dragon_head|minecraft:skeleton_wall_skull|minecraft:wither_skeleton_wall_skull|minecraft:zombie_wall_head|minecraft:player_wall_head|minecraft:creeper_wall_head|minecraft:dragon_wall_head", "1.12:skull(144,d0-4)；1.13 拆各种 *_skull/*_head。本图集一张（通用头），覆盖全部" },
    { "Anvil",                       145, 0,   "minecraft:anvil",                "minecraft:chipped_anvil|minecraft:damaged_anvil", "1.12:anvil(145,d0-2)；1.13 拆 anvil/chipped/damaged" },
    { "Trapped_Chest",               146, -1,  "minecraft:trapped_chest",        "",                                   "1.12:trapped_chest(146)" },
    { "Light_Weighted_Pressure_Plate",147, -1, "minecraft:light_weighted_pressure_plate", "",                            "1.12:light_weighted_pressure_plate(147)" },
    { "Heavy_Weighted_Pressure_Plate",148, -1, "minecraft:heavy_weighted_pressure_plate", "",                           "1.12:heavy_weighted_pressure_plate(148)" },
    { "Redstone_Comparator",         149, -1,  "minecraft:comparator",           "minecraft:unpowered_comparator|minecraft:powered_comparator", "1.12:unpowered_comparator(149)/powered_comparator(150)；1.13 合并为 comparator" },
    { "Daylight_Sensor",             151, -1,  "minecraft:daylight_detector",    "minecraft:daylight_detector_inverted", "1.12:daylight_detector(151)/inverted(178)；1.13 合并（inverted 为状态）" },
    { "Block_of_Redstone",           152, -1,  "minecraft:redstone_block",       "",                                   "1.12:redstone_block(152)" },
    { "Hopper",                      154, -1,  "minecraft:hopper",               "",                                   "1.12:hopper(154)" },
    { "Block_of_Quartz",             155, 0,   "minecraft:quartz_block",         "minecraft:chiseled_quartz_block|minecraft:quartz_pillar|minecraft:smooth_quartz|minecraft:quartz_bricks", "1.12:quartz_block(155,d0-3)；1.13 拆 quartz_block/chiseled/pillar/smooth/bricks" },
    { "Quartz_Stairs",               156, -1,  "minecraft:quartz_stairs",         "",                                   "1.12:quartz_stairs(156)" },
    { "Dropper",                     158, -1,  "minecraft:dropper",              "",                                   "1.12:dropper(158)" },
    { "Colored_Terracotta",          159, 0,   "minecraft:white_terracotta",     "minecraft:orange_terracotta|minecraft:magenta_terracotta|minecraft:light_blue_terracotta|minecraft:yellow_terracotta|minecraft:lime_terracotta|minecraft:pink_terracotta|minecraft:gray_terracotta|minecraft:light_gray_terracotta|minecraft:cyan_terracotta|minecraft:purple_terracotta|minecraft:blue_terracotta|minecraft:brown_terracotta|minecraft:green_terracotta|minecraft:red_terracotta|minecraft:black_terracotta", "1.12:stained_hardened_clay(159,d0-15)；1.13 拆 16 色 *_terracotta（本图集一张，覆盖全色）" },
    { "Stained_Glass_Pane",          160, 0,   "minecraft:white_stained_glass_pane", "minecraft:orange_stained_glass_pane|minecraft:magenta_stained_glass_pane|minecraft:light_blue_stained_glass_pane|minecraft:yellow_stained_glass_pane|minecraft:lime_stained_glass_pane|minecraft:pink_stained_glass_pane|minecraft:gray_stained_glass_pane|minecraft:light_gray_stained_glass_pane|minecraft:cyan_stained_glass_pane|minecraft:purple_stained_glass_pane|minecraft:blue_stained_glass_pane|minecraft:brown_stained_glass_pane|minecraft:green_stained_glass_pane|minecraft:red_stained_glass_pane|minecraft:black_stained_glass_pane", "1.12:stained_glass_pane(160,d0-15)；1.13 拆 16 色 *_stained_glass_pane（本图集一张，覆盖全色）" },
    { "Acacia_Leaves",               161, 0,   "minecraft:acacia_leaves",        "",                                   "1.12:leaves2(161,d0)；1.13 拆 acacia_leaves/dark_oak_leaves" },
    { "Acacia_Log",                  162, 0,   "minecraft:acacia_log",           "",                                   "1.12:log2(162,d0)；1.13 拆 acacia_log/dark_oak_log" },
    { "Acacia_Stairs",              163, -1,  "minecraft:acacia_stairs",        "",                                   "1.12:acacia_stairs(163)" },
    { "Dark_Oak_Stairs",            164, -1,  "minecraft:dark_oak_stairs",       "",                                   "1.12:dark_oak_stairs(164)" },
    { "Slime_Block",                 165, -1,  "minecraft:slime_block",          "",                                   "1.12:slime_block(165)；1.13 重命名 slime" },
    { "Iron_Trapdoor",               167, -1,  "minecraft:iron_trapdoor",        "",                                   "1.12:iron_trapdoor(167)" },
    { "Prismarine",                  168, 0,   "minecraft:prismarine",           "minecraft:prismarine_bricks|minecraft:dark_prismarine", "1.12:prismarine(168,d0-2)；1.13 拆 prismarine/prismarine_bricks/dark_prismarine" },
    { "Sea_Lantern",                 169, -1,  "minecraft:sea_lantern",           "",                                   "1.12:sea_lantern(169)" },
    { "Carpet",                      171, 0,   "minecraft:white_carpet",         "minecraft:orange_carpet|minecraft:magenta_carpet|minecraft:light_blue_carpet|minecraft:yellow_carpet|minecraft:lime_carpet|minecraft:pink_carpet|minecraft:gray_carpet|minecraft:light_gray_carpet|minecraft:cyan_carpet|minecraft:purple_carpet|minecraft:blue_carpet|minecraft:brown_carpet|minecraft:green_carpet|minecraft:red_carpet|minecraft:black_carpet", "1.12:carpet(171,d0-15)；1.13 拆 16 色 *_carpet（本图集一张，覆盖全色）" },
    { "Terracotta",                  172, -1,  "minecraft:terracotta",          "minecraft:hardened_clay",              "1.12:hardened_clay(172)；1.13 重命名 terracotta" },
    { "Block_of_Coal",               173, -1,  "minecraft:coal_block",           "",                                   "1.12:coal_block(173)" },
    { "Packed_Ice",                  174, -1,  "minecraft:packed_ice",           "",                                   "1.12:packed_ice(174)" },
    { "Sunflower",                   175, 0,   "minecraft:sunflower",            "minecraft:lilac|minecraft:tall_grass|minecraft:large_fern|minecraft:rose_bush|minecraft:peony", "1.12:double_plant(175,d0-5)；1.13 拆 6 种大型植物。本图集一张（通用大花），覆盖全部" },
    { "Wall_Banner",                177, -1,  "minecraft:white_wall_banner",     "minecraft:orange_wall_banner|minecraft:magenta_wall_banner|minecraft:light_blue_wall_banner|minecraft:yellow_wall_banner|minecraft:lime_wall_banner|minecraft:pink_wall_banner|minecraft:gray_wall_banner|minecraft:light_gray_wall_banner|minecraft:cyan_wall_banner|minecraft:purple_wall_banner|minecraft:blue_wall_banner|minecraft:brown_wall_banner|minecraft:green_wall_banner|minecraft:red_wall_banner|minecraft:black_wall_banner|minecraft:white_banner|minecraft:orange_banner|minecraft:magenta_banner|minecraft:light_blue_banner|minecraft:yellow_banner|minecraft:lime_banner|minecraft:pink_banner|minecraft:gray_banner|minecraft:light_gray_banner|minecraft:cyan_banner|minecraft:purple_banner|minecraft:blue_banner|minecraft:brown_banner|minecraft:green_banner|minecraft:red_banner|minecraft:black_banner", "1.12:wall_banner(177)/banner(176)；1.13 拆 16 色 *_banner + *_wall_banner（本图集一张，覆盖全部）" },
    { "Red_Sandstone",              179, -1,  "minecraft:red_sandstone",        "minecraft:chiseled_red_sandstone|minecraft:cut_red_sandstone|minecraft:smooth_red_sandstone", "1.12:red_sandstone(179,d0-2)；1.13 拆 red_sandstone/chiseled/cut/smooth" },
    { "Double_Red_Sandstone_Slab",   177, -1, "minecraft:double_red_sandstone_slab", "",                               "1.12:double_stone_slab2(177)；1.13 拆 double_red_sandstone_slab 等" },
    { "Red_Sandstone_Slab",          178, -1,  "minecraft:red_sandstone_slab",   "",                                   "1.12:stone_slab2(178)；1.13 拆 red_sandstone_slab 等" },
    { "Spruce_Fence_Gate",           181, -1,  "minecraft:spruce_fence_gate",    "",                                   "1.12:spruce_fence_gate(181)" },
    { "Birch_Fence_Gate",            182, -1,  "minecraft:birch_fence_gate",     "",                                   "1.12:birch_fence_gate(182)" },
    { "Spruce_Fence",                186, -1,  "minecraft:spruce_fence",         "",                                   "1.12:spruce_fence(186)" },
    { "Birch_Fence",                 187, -1,  "minecraft:birch_fence",          "",                                   "1.12:birch_fence(187)" },
    { "Jungle_Fence",                188, -1,  "minecraft:jungle_fence",         "",                                   "1.12:jungle_fence(188)" },
    { "Dark_Oak_Fence",              189, -1,  "minecraft:dark_oak_fence",       "",                                   "1.12:dark_oak_fence(189)" },
    { "Acacia_Fence",                190, -1,  "minecraft:acacia_fence",         "",                                   "1.12:acacia_fence(190)" },
    { "Spruce_Door",                 191, -1,  "minecraft:spruce_door",          "",                                   "1.12:spruce_door(191)" },
    { "Birch_Door",                  192, -1,  "minecraft:birch_door",           "",                                   "1.12:birch_door(192)" },
    { "Jungle_Door",                 193, -1,  "minecraft:jungle_door",          "",                                   "1.12:jungle_door(193)" },
    { "Acacia_Door",                 194, -1,  "minecraft:acacia_door",          "",                                   "1.12:acacia_door(194)" },
    { "Dark_Oak_Door",               195, -1,  "minecraft:dark_oak_door",        "",                                   "1.12:dark_oak_door(195)" },
    { "End_Rod",                     198, -1,  "minecraft:end_rod",              "",                                   "1.12:end_rod(198)" },
    { "Purpur_Slab",                 203, -1,  "minecraft:purpur_slab",          "minecraft:double_purpur_slab|minecraft:purpur_block|minecraft:purpur_pillar|minecraft:purpur_stairs", "1.12:purpur_block(199)/purpur_pillar(200)/purpur_stairs(201)/purpur_double_slab(202)/purpur_slab(203)；1.13 命名整理" },
    { "Magma_Block",                 213, -1,  "minecraft:magma_block",          "minecraft:magma",                      "1.12:magma(213)；1.13 重命名 magma_block" },
    { "Bone_Block",                  216, -1,  "minecraft:bone_block",           "",                                   "1.12:bone_block(216)" },
    { "Observer",                    218, -1,  "minecraft:observer",             "",                                   "1.12:observer(218)" },
    { "Light_Grey_Shulker_Box",      219, 8,   "minecraft:light_gray_shulker_box", "",                                 "1.12:shulker_box(219,d0-15)；1.13 拆 16 色 *_shulker_box（本 MTL 为浅灰，特定色 d8）" },
    { "Purple_Shulker_Box",          219, 10,  "minecraft:purple_shulker_box",  "",                                   "1.12:shulker_box(219,d10=紫)；1.13 拆 16 色。本 MTL 为紫，特定色" },
    { "Red_Shulker_Box",             219, 14,  "minecraft:red_shulker_box",      "",                                   "1.12:shulker_box(219,d14=红)；1.13 拆 16 色。本 MTL 为红，特定色" },
    { "White_Glazed_Terracotta",     235, 0,   "minecraft:white_glazed_terracotta", "",                                "1.12:glazed_terracotta(235,d0-15)；1.13 拆 16 色 *_glazed_terracotta（本 MTL 白，特定色 d0=白）" },
    { "Magenta_Glazed_Terracotta",   235, 2,   "minecraft:magenta_glazed_terracotta", "",                              "本 MTL 品红，特定色" },
    { "Light_Blue_Glazed_Terracotta",235, 3,   "minecraft:light_blue_glazed_terracotta", "",                           "本 MTL 浅蓝，特定色" },
    { "Yellow_Glazed_Terracotta",    235, 4,   "minecraft:yellow_glazed_terracotta", "",                                "本 MTL 黄，特定色" },
    { "Lime_Glazed_Terracotta",      235, 5,   "minecraft:lime_glazed_terracotta", "",                                 "本 MTL 黄绿，特定色" },
    { "Gray_Glazed_Terracotta",      235, 7,   "minecraft:gray_glazed_terracotta", "",                                 "本 MTL 灰，特定色" },
    { "Light_Grey_Glazed_Terracotta",235, 8,   "minecraft:light_gray_glazed_terracotta", "",                           "本 MTL 浅灰，特定色" },
    { "Blue_Glazed_Terracotta",      235, 11,  "minecraft:blue_glazed_terracotta", "",                                 "本 MTL 蓝，特定色" },
    { "Green_Glazed_Terracotta",     235, 13,  "minecraft:green_glazed_terracotta", "",                                 "本 MTL 绿，特定色" },
    { "Red_Glazed_Terracotta",       235, 14,  "minecraft:red_glazed_terracotta", "",                                  "本 MTL 红，特定色" },
    { "Black_Glazed_Terracotta",     235, 15,  "minecraft:black_glazed_terracotta", "",                                "本 MTL 黑，特定色" },
    { "Concrete",                    236, 0,   "minecraft:white_concrete",       "minecraft:orange_concrete|minecraft:magenta_concrete|minecraft:light_blue_concrete|minecraft:yellow_concrete|minecraft:lime_concrete|minecraft:pink_concrete|minecraft:gray_concrete|minecraft:light_gray_concrete|minecraft:cyan_concrete|minecraft:purple_concrete|minecraft:blue_concrete|minecraft:brown_concrete|minecraft:green_concrete|minecraft:red_concrete|minecraft:black_concrete", "1.12:无（1.13 新增）；拆 16 色 *_concrete（本图集一张，覆盖全色）" },
    { "Concrete_Powder",             237, 0,   "minecraft:white_concrete_powder", "minecraft:orange_concrete_powder|minecraft:magenta_concrete_powder|minecraft:light_blue_concrete_powder|minecraft:yellow_concrete_powder|minecraft:lime_concrete_powder|minecraft:pink_concrete_powder|minecraft:gray_concrete_powder|minecraft:light_gray_concrete_powder|minecraft:cyan_concrete_powder|minecraft:purple_concrete_powder|minecraft:blue_concrete_powder|minecraft:brown_concrete_powder|minecraft:green_concrete_powder|minecraft:red_concrete_powder|minecraft:black_concrete_powder", "1.12:无（1.13 新增）；拆 16 色 *_concrete_powder（本图集一张，覆盖全色）" },
    { "Structure_Block",             255, -1,  "minecraft:structure_block",      "",                                   "1.12:structure_block(255)" },
    { "Dark_Prismarine_Stairs",      -1,  -1,  "minecraft:dark_prismarine_stairs", "",                                 "1.12:无（1.13 新增）；prismarine 楼梯" },
    { "Spruce_Trapdoor",             -1,  -1,  "minecraft:spruce_trapdoor",      "",                                   "1.13 新增" },
    { "Birch_Trapdoor",              -1,  -1,  "minecraft:birch_trapdoor",       "",                                   "1.13 新增" },
    { "Jungle_Trapdoor",             -1,  -1,  "minecraft:jungle_trapdoor",      "",                                   "1.13 新增" },
    { "Acacia_Trapdoor",             -1,  -1,  "minecraft:acacia_trapdoor",      "",                                   "1.13 新增" },
    { "Dark_Oak_Trapdoor",           -1,  -1,  "minecraft:dark_oak_trapdoor",    "",                                   "1.13 新增" },
    { "Acacia_Button",               -1,  -1,  "minecraft:acacia_button",        "",                                   "1.13 新增" },
    { "Dark_Oak_Button",             -1,  -1,  "minecraft:dark_oak_button",      "",                                   "1.13 新增" },
    { "Spruce_Pressure_Plate",       -1,  -1,  "minecraft:spruce_pressure_plate","",                                   "1.13 新增" },
    { "Stripped_Oak_Log",            -1,  -1,  "minecraft:stripped_oak_log",     "",                                   "1.13 新增 stripped_*" },
    { "Stripped_Acacia_Wood",        -1,  -1,  "minecraft:stripped_acacia_wood", "",                                  "1.13 新增 stripped_*_wood" },
    { "Light_Blue_Wall_Banner",      -1,  -1,  "minecraft:light_blue_wall_banner", "minecraft:light_blue_banner",      "1.13 新增具体色 banner" },
    { "Black_Wall_Banner",           -1,  -1,  "minecraft:black_wall_banner",    "minecraft:black_banner",             "1.13 新增具体色 banner" },
    { "Smooth_Stone",                -1,  -1,  "minecraft:smooth_stone",         "",                                   "1.13 新增" },
    { "Blue_Ice",                    -1,  -1,  "minecraft:blue_ice",              "",                                   "1.13 新增" },
    { "Dried_Kelp_Block",            -1,  -1,  "minecraft:dried_kelp_block",     "",                                   "1.13 新增" },
    { "Dead_Coral_Block",            -1,  -1,  "minecraft:dead_brain_coral_block","minecraft:dead_bubble_coral_block|minecraft:dead_fire_coral_block|minecraft:dead_horn_coral_block|minecraft:dead_tube_coral_block", "1.13 新增珊瑚（死）；本图集一张（通用死珊瑚块），覆盖全部" },
    { "Dead_Coral_Fan",              -1,  -1,  "minecraft:dead_brain_coral_fan", "minecraft:dead_bubble_coral_fan|minecraft:dead_fire_coral_fan|minecraft:dead_horn_coral_fan|minecraft:dead_tube_coral_fan", "1.13 新增珊瑚扇（死）；本图集一张，覆盖全部" },
    { "Conduit",                     -1,  -1,  "minecraft:conduit",              "",                                   "1.13 新增" },
    { "Bamboo",                      -1,  -1,  "minecraft:bamboo",               "",                                   "1.13 新增" },
    { "Double_Andesite_Slab",        -1,  -1,  "minecraft:double_andesite_slab", "",                                  "1.13 新增各类石头 slab" },
    { "Andesite_Slab",               -1,  -1,  "minecraft:andesite_slab",        "",                                   "1.13 新增" },
    { "Composter",                   -1,  -1,  "minecraft:composter",            "",                                   "1.14 新增" },
    { "Barrel",                      -1,  -1,  "minecraft:barrel",               "",                                   "1.14 新增" },
    { "Grindstone",                  -1,  -1,  "minecraft:grindstone",           "",                                   "1.14 新增" },
    { "Lectern",                     -1,  -1,  "minecraft:lectern",              "",                                   "1.14 新增" },
    { "Bell",                        -1,  -1,  "minecraft:bell",                 "",                                   "1.14 新增" },
    { "Lantern",                     -1,  -1,  "minecraft:lantern",              "",                                   "1.14 新增" },
    { "Campfire",                    -1,  -1,  "minecraft:campfire",             "minecraft:soul_campfire",             "1.14 新增" },
    { "Bee_Nest",                    -1,  -1,  "minecraft:bee_nest",             "minecraft:beehive",                   "1.15 新增" },
    { "Honey_Block",                 -1,  -1,  "minecraft:honey_block",          "",                                   "1.15 新增" },
    { "Crimson_Button",              -1,  -1,  "minecraft:crimson_button",       "",                                   "1.16 新增下界更新" },
    { "Warped_Button",               -1,  -1,  "minecraft:warped_button",        "",                                   "1.16 新增" },
    { "Polished_Blackstone_Button",  -1,  -1,  "minecraft:polished_blackstone_button", "",                             "1.16 新增" },
    { "Polished_Blackstone_Pressure_Plate", -1, -1, "minecraft:polished_blackstone_pressure_plate", "",                "1.16 新增" },
    { "Crimson_Slab",                -1,  -1,  "minecraft:crimson_slab",         "",                                   "1.16 新增" },
    { "Chain",                       -1,  -1,  "minecraft:chain",                "",                                   "1.16 新增" },
    { "Stone_Stairs",                -1,  -1,  "minecraft:stone_stairs",         "",                                   "1.13 新增（普通石头楼梯）" },
    { "Polished_Granite_Stairs",     -1,  -1,  "minecraft:polished_granite_stairs", "",                               "1.13 新增" },
    { "Smooth_Quartz_Stairs",        -1,  -1,  "minecraft:smooth_quartz_stairs", "",                                  "1.13 新增" },
    { "Polished_Diorite_Stairs",     -1,  -1,  "minecraft:polished_diorite_stairs", "",                               "1.13 新增" },
    { "End_Stone_Brick_Stairs",      -1,  -1,  "minecraft:end_stone_brick_stairs", "",                                "1.13 新增" },
    { "Andesite_Stairs",             -1,  -1,  "minecraft:andesite_stairs",      "",                                   "1.13 新增" },
    { "Polished_Andesite_Stairs",    -1,  -1,  "minecraft:polished_andesite_stairs", "",                              "1.13 新增" },
    { "Mossy_Stone_Brick_Stairs",    -1,  -1,  "minecraft:mossy_stone_brick_stairs", "",                              "1.13 新增" },
    { "Mossy_Cobblestone_Stairs",    -1,  -1,  "minecraft:mossy_cobblestone_stairs", "",                              "1.13 新增" },
    { "Smooth_Sandstone_Stairs",     -1,  -1,  "minecraft:smooth_sandstone_stairs", "",                               "1.13 新增" },
    { "Polished_Blackstone_Stairs",  -1,  -1,  "minecraft:polished_blackstone_stairs", "",                             "1.16 新增" },
    { "Candle",                      -1,  -1,  "minecraft:candle",               "minecraft:white_candle|minecraft:orange_candle|minecraft:magenta_candle|minecraft:light_blue_candle|minecraft:yellow_candle|minecraft:lime_candle|minecraft:pink_candle|minecraft:gray_candle|minecraft:light_gray_candle|minecraft:cyan_candle|minecraft:purple_candle|minecraft:blue_candle|minecraft:brown_candle|minecraft:green_candle|minecraft:red_candle|minecraft:black_candle", "1.17 新增；拆 16 色 + 多层蜡烛。本图集一张（蜡烛），覆盖白色基础款" },
    { "White_Candle",                -1,  -1,  "minecraft:white_candle",         "",                                   "1.17 新增（与 Candle 同基础贴图）" },
    { "Lit_White_Candle",            -1,  -1,  "minecraft:lit_candle",           "",                                   "1.17 新增（点燃蜡烛，lit 为状态）" },
    { "Block_of_Amethyst",           -1,  -1,  "minecraft:amethyst_block",       "",                                   "1.17 新增" },
    { "Small_Amethyst_Bud",          -1,  -1,  "minecraft:small_amethyst_bud",   "minecraft:medium_amethyst_bud|minecraft:large_amethyst_bud|minecraft:amethyst_cluster", "1.17 新增紫晶簇系列；本图集一张（小芽），覆盖同款" },
    { "Exposed_Cut_Copper_Stairs",   -1,  -1,  "minecraft:exposed_cut_copper_stairs", "minecraft:weathered_cut_copper_stairs|minecraft:oxidized_cut_copper_stairs|minecraft:cut_copper_stairs|minecraft:waxed_cut_copper_stairs|minecraft:waxed_exposed_cut_copper_stairs|minecraft:waxed_weathered_cut_copper_stairs|minecraft:waxed_oxidized_cut_copper_stairs", "1.17 新增铜楼梯系列（氧化阶段）；本图集一张（暴露），覆盖同款" },
    { "Weathered_Cut_Copper_Stairs", -1,  -1,  "minecraft:weathered_cut_copper_stairs", "",                           "1.17 新增铜楼梯（风化）" },
    { "Oxidized_Cut_Copper_Stairs",  -1,  -1,  "minecraft:oxidized_cut_copper_stairs", "",                            "1.17 新增铜楼梯（氧化）" },
    { "Lightning_Rod",               -1,  -1,  "minecraft:lightning_rod",        "",                                   "1.17 新增" },
    { "Double_Cut_Copper_Slab",      -1,  -1,  "minecraft:double_cut_copper_slab", "minecraft:cut_copper_slab|minecraft:exposed_cut_copper_slab|minecraft:weathered_cut_copper_slab|minecraft:oxidized_cut_copper_slab|minecraft:waxed_cut_copper_slab|minecraft:waxed_exposed_cut_copper_slab|minecraft:waxed_weathered_cut_copper_slab|minecraft:waxed_oxidized_cut_copper_slab", "1.17 新增铜半砖系列；本图集一张（双铜半砖），覆盖同款" },
    { "Cut_Copper_Slab",             -1,  -1,  "minecraft:cut_copper_slab",      "",                                   "1.17 新增铜半砖" },
    { "Waxed_Cut_Copper_Stairs",     -1,  -1,  "minecraft:waxed_cut_copper_stairs", "",                               "1.17 新增（打蜡铜楼梯）" },
    { "Waxed_Weathered_Cut_Copper_Stairs", -1, -1, "minecraft:waxed_weathered_cut_copper_stairs", "",                  "1.17 新增（打蜡风化铜楼梯）" },
    { "Cave_Vines",                  -1,  -1,  "minecraft:cave_vines",           "minecraft:cave_vines_plant",          "1.17 新增洞穴藤蔓" },
    { "Cave_Vines_lit",              -1,  -1,  "minecraft:cave_vines",           "",                                   "1.17 洞穴藤蔓（发光态，lit 为状态）" },
    { "Polished_Deepslate_Stairs",   -1,  -1,  "minecraft:polished_deepslate_stairs", "",                             "1.17 新增深板岩楼梯" },
    { "Deepslate_Tile_Stairs",       -1,  -1,  "minecraft:deepslate_tile_stairs", "",                                 "1.17 新增深板岩砖楼梯" },

    // ---- glass1.mtl 的玻璃透显变体（与 ss1 同名，使用 glass1-RGB.png + alpha）----
    { "Grass_Block",                 2,   -1,  "minecraft:grass_block",          "",                                   "glass1.mtl：Grass_Block 的玻璃透显版（见 glass1-RGB.png）" },
    { "Dirt",                        3,   -1,  "minecraft:dirt",                  "",                                   "glass1.mtl：Dirt 的玻璃透显版" },
    { "Cobblestone",                 4,   -1,  "minecraft:cobblestone",          "",                                   "glass1.mtl：Cobblestone 的玻璃透显版" },
    { "Bedrock",                     7,   -1,  "minecraft:bedrock",              "",                                   "glass1.mtl：Bedrock 的玻璃透显版" },
    { "Stationary_Lava",             10,  -1,  "minecraft:lava",                 "minecraft:flowing_lava",              "glass1.mtl：熔岩的玻璃透显版（1.12:lava(10,静)/flowing_lava(11,流)）" },
    { "Obsidian",                    49,  -1,  "minecraft:obsidian",             "",                                   "glass1.mtl：Obsidian 的玻璃透显版" },
};

static const int g_mcBlockMapCount = (int)(sizeof(g_mcBlockMap) / sizeof(g_mcBlockMap[0]));
